- name: Ensure RHACM MultiClusterHub is present
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: operator.open-cluster-management.io/v1
      kind: MultiClusterHub
      metadata:
        name: multiclusterhub
        namespace: open-cluster-management
      spec: {}
  retries: 60
  delay: 10
  register: r_mhc
  until: r_mhc is succeeded

- name: Wait until RHACM MultiClusterHub is ready
  kubernetes.core.k8s_info:
    api_version: operator.open-cluster-management.io/v1
    kind: MultiClusterHub
    name: multiclusterhub
    namespace: open-cluster-management
  register: rhacm_multiclusterhub
  retries: 120
  delay: 30
  until:
  - rhacm_multiclusterhub is defined
  - rhacm_multiclusterhub.resources is defined
  - rhacm_multiclusterhub.resources | length > 0
  - rhacm_multiclusterhub.resources[0].status is defined
  - rhacm_multiclusterhub.resources[0].status.phase is defined
  - rhacm_multiclusterhub.resources[0].status.phase == "Running"

- name: Create Namespace for policies
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: openshift-acm-policies

- name: Add ManagedClusterSetBinding
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: cluster.open-cluster-management.io/v1beta2
      kind: ManagedClusterSetBinding
      metadata:
        name: default
        namespace: openshift-acm-policies
      spec:
        clusterSet: default

- name: Create Placement for policies
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: cluster.open-cluster-management.io/v1beta1
      kind: Placement
      metadata:
        name: placement-local
        namespace: openshift-acm-policies
      spec:
        predicates:
          - requiredClusterSelector:
              labelSelector:
                matchExpressions:
                  - key: name
                    operator: In
                    values:
                      - local-cluster

- name: ACM ClusterImageSet reconciliation
  ansible.builtin.include_tasks:
    file: acm_cis.yaml
