- name: Ensure RHACM MultiClusterHub is present
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: operator.open-cluster-management.io/v1
      kind: MultiClusterHub
      metadata:
        name: multiclusterhub
        namespace: open-cluster-management
      spec: {}
  retries: 60
  delay: 10
  register: r_mhc
  until: r_mhc is succeeded

- name: Wait until RHACM MultiClusterHub is ready
  kubernetes.core.k8s_info:
    api_version: operator.open-cluster-management.io/v1
    kind: MultiClusterHub
    name: multiclusterhub
    namespace: open-cluster-management
  register: rhacm_multiclusterhub
  retries: 120
  delay: 30
  until:
  - rhacm_multiclusterhub is defined
  - rhacm_multiclusterhub.resources is defined
  - rhacm_multiclusterhub.resources | length > 0
  - rhacm_multiclusterhub.resources[0].status is defined
  - rhacm_multiclusterhub.resources[0].status.phase is defined
  - rhacm_multiclusterhub.resources[0].status.phase == "Running"

- name: Create Namespace for policies
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: openshift-acm-policies

- name: Add ManagedClusterSetBinding
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: cluster.open-cluster-management.io/v1beta2
      kind: ManagedClusterSetBinding
      metadata:
        name: default
        namespace: openshift-acm-policies
      spec:
        clusterSet: default

- name: Create Placement for policies
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: cluster.open-cluster-management.io/v1beta1
      kind: Placement
      metadata:
        name: placement-local
        namespace: openshift-acm-policies
      spec:
        predicates:
          - requiredClusterSelector:
              labelSelector:
                matchExpressions:
                  - key: name
                    operator: In
                    values:
                      - local-cluster

- name: Create Configmap for disconnected
  when: disconnected | default(true)
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: custom-registries
        namespace: multicluster-engine
        labels:
          app: assisted-service
      data:
        ca-bundle.crt: |
          {{ lookup('file', quayCAPath) }}
          {{ sslAPICertificateFullChain | default('') }}
        registries.conf: |
          unqualified-search-registries = ["registry.access.redhat.com", "docker.io"]

          [[registry]]
            prefix = ""
            location="quay.io/openshift-release-dev/ocp-v4.0-art-dev"
            mirror-by-digest-only=true
          [[registry.mirror]]
            location="registry-quay-quay-enterprise.apps.{{ clusterName }}.{{ baseDomain }}/openshift/release"

          [[registry]]
            prefix = ""
            location="registry.redhat.io/openshift"
            mirror-by-digest-only=true
          [[registry.mirror]]
            location="registry-quay-quay-enterprise.apps.{{ clusterName }}.{{ baseDomain }}/openshift"

          [[registry]]
            prefix = ""
            location = "registry.redhat.io/openshift-pipelines"
            mirror-by-digest-only=true
          [[registry.mirror]]
            location = "registry-quay-quay-enterprise.apps.{{ clusterName }}.{{ baseDomain }}/openshift-pipelines"

          [[registry]]
            prefix = ""
            location = "registry.redhat.io/openshift4"
          [[registry.mirror]]
            location = "registry-quay-quay-enterprise.apps.{{ clusterName }}.{{ baseDomain }}/openshift4"

          [[registry]]
            prefix = ""
            location = "registry.redhat.io/openshift-gitops-1"
          [[registry.mirror]]
            location = "registry-quay-quay-enterprise.apps.{{ clusterName }}.{{ baseDomain }}/openshift-gitops-1"

          [[registry]]
            prefix = ""
            location = "registry.redhat.io/rhel8"
          [[registry.mirror]]
            location = "registry-quay-quay-enterprise.apps.{{ clusterName }}.{{ baseDomain }}/rhel8"

          [[registry]]
            prefix = ""
            location = "registry.redhat.io/source-to-image"
          [[registry.mirror]]
            location = "registry-quay-quay-enterprise.apps.{{ clusterName }}.{{ baseDomain }}/source-to-image"

          [[registry]]
            prefix = ""
            location = "registry.redhat.io/ubi8"
          [[registry.mirror]]
            location = "registry-quay-quay-enterprise.apps.{{ clusterName }}.{{ baseDomain }}/ubi8"

          [[registry]]
            prefix = ""
            location = "registry.redhat.io/ubi9"
          [[registry.mirror]]
            location = "registry-quay-quay-enterprise.apps.{{ clusterName }}.{{ baseDomain }}/ubi9"

          [[registry]]
            prefix = ""
            location = "registry.redhat.io/multicluster-engine"
          [[registry.mirror]]
            location = "registry-quay-quay-enterprise.apps.{{ clusterName }}.{{ baseDomain }}/multicluster-engine"

          [[registry]]
            prefix = ""
            location = "registry.redhat.io/quay"
          [[registry.mirror]]
            location = "registry-quay-quay-enterprise.apps.{{ clusterName }}.{{ baseDomain }}/quay"

          [[registry]]
            prefix = ""
            location = "registry.redhat.io/rhel9"
          [[registry.mirror]]
            location = "registry-quay-quay-enterprise.apps.{{ clusterName }}.{{ baseDomain }}/rhel9"

          [[registry]]
            prefix = ""
            location = "registry.redhat.io/rhacm2"
          [[registry.mirror]]
            location = "registry-quay-quay-enterprise.apps.{{ clusterName }}.{{ baseDomain }}/rhacm2"

          [[registry]]
            prefix = ""
            location = "registry.redhat.io/rhem"
          [[registry.mirror]]
            location = "registry-quay-quay-enterprise.apps.{{ clusterName }}.{{ baseDomain }}/rhem"

          [[registry]]
            prefix = ""
            location = "registry.redhat.io/container-native-virtualization"
          [[registry.mirror]]
            location = "registry-quay-quay-enterprise.apps.{{ clusterName }}.{{ baseDomain }}/container-native-virtualization"

          [[registry]]
            prefix = ""
            location = "registry.redhat.io/rh-sso-7"
          [[registry.mirror]]
            location = "registry-quay-quay-enterprise.apps.{{ clusterName }}.{{ baseDomain }}/rh-sso-7"

          [[registry]]
            prefix = ""
            location = "registry.redhat.io/openshift-logging"
          [[registry.mirror]]
            location = "registry-quay-quay-enterprise.apps.{{ clusterName }}.{{ baseDomain }}/openshift-logging"

          [[registry]]
            prefix = ""
            location = "registry.redhat.io/oadp"
          [[registry.mirror]]
            location = "registry-quay-quay-enterprise.apps.{{ clusterName }}.{{ baseDomain }}/oadp"

          [[registry]]
            prefix = ""
            location = "registry.redhat.io/network-observability"
          [[registry.mirror]]
            location = "registry-quay-quay-enterprise.apps.{{ clusterName }}.{{ baseDomain }}/network-observability"

          [[registry]]
            prefix = ""
            location = "registry.redhat.io/migration-toolkit-virtualization"
          [[registry.mirror]]
            location = "registry-quay-quay-enterprise.apps.{{ clusterName }}.{{ baseDomain }}/migration-toolkit-virtualization"

          [[registry]]
            prefix = ""
            location = "registry.redhat.io/openshift-serverless-1"
          [[registry.mirror]]
            location = "registry-quay-quay-enterprise.apps.{{ clusterName }}.{{ baseDomain }}/openshift-serverless-1"

          [[registry]]
            prefix = ""
            location = "registry.redhat.io/lvms4"
          [[registry.mirror]]
            location = "registry-quay-quay-enterprise.apps.{{ clusterName }}.{{ baseDomain }}/lvms4"

          [[registry]]
            prefix = ""
            location = "registry.redhat.io/odf4"
          [[registry.mirror]]
            location = "registry-quay-quay-enterprise.apps.{{ clusterName }}.{{ baseDomain }}/odf4"

          [[registry]]
            prefix = ""
            location = "registry.redhat.io/rhceph"
          [[registry.mirror]]
            location = "registry-quay-quay-enterprise.apps.{{ clusterName }}.{{ baseDomain }}/rhceph"

          [[registry]]
            prefix = ""
            location = "registry.redhat.io/cert-manager"
          [[registry.mirror]]
            location = "registry-quay-quay-enterprise.apps.{{ clusterName }}.{{ baseDomain }}/cert-manager"

          [[registry]]
            prefix = ""
            location = "registry.redhat.io/cluster-observability-operator"
          [[registry.mirror]]
            location = "registry-quay-quay-enterprise.apps.{{ clusterName }}.{{ baseDomain }}/cluster-observability-operator"

          [[registry]]
            prefix = ""
            location = "registry.redhat.io/external-secrets-operator"
          [[registry.mirror]]
            location = "registry-quay-quay-enterprise.apps.{{ clusterName }}.{{ baseDomain }}/external-secrets-operator"

          [[registry]]
            prefix = ""
            location = "registry.redhat.io/compliance"
          [[registry.mirror]]
            location = "registry-quay-quay-enterprise.apps.{{ clusterName }}.{{ baseDomain }}/compliance"

          [[registry]]
            prefix = ""
            location = "nvcr.io/nvidia"
          [[registry.mirror]]
            location = "registry-quay-quay-enterprise.apps.{{ clusterName }}.{{ baseDomain }}/nvidia"

          [[registry]]
            prefix = ""
            location = "registry.connect.redhat.com/nvidia"
          [[registry.mirror]]
            location = "registry-quay-quay-enterprise.apps.{{ clusterName }}.{{ baseDomain }}/nvidia"

          [[registry]]
            prefix = ""
            location = "registry.connect.redhat.com/hashicorp"
          [[registry.mirror]]
            location = "registry-quay-quay-enterprise.apps.{{ clusterName }}.{{ baseDomain }}/hashicorp"

          [[registry]]
            prefix = ""
            location = "registry.redhat.io/rhcl-1"
          [[registry.mirror]]
            location = "registry-quay-quay-enterprise.apps.{{ clusterName }}.{{ baseDomain }}/rhcl-1"

          [[registry]]
            prefix = ""
            location = "registry.redhat.io/leader-worker-set"
          [[registry.mirror]]
            location = "registry-quay-quay-enterprise.apps.{{ clusterName }}.{{ baseDomain }}/leader-worker-set"

          [[registry]]
            prefix = ""
            location = "registry.redhat.io/openshift-service-mesh"
          [[registry.mirror]]
            location = "registry-quay-quay-enterprise.apps.{{ clusterName }}.{{ baseDomain }}/openshift-service-mesh"

          [[registry]]
            prefix = ""
            location = "registry.redhat.io/openshift-service-mesh-tech-preview"
          [[registry.mirror]]
            location = "registry-quay-quay-enterprise.apps.{{ clusterName }}.{{ baseDomain }}/openshift-service-mesh-tech-preview"

          [[registry]]
            prefix = ""
            location = "registry.redhat.io/openshift-service-mesh-dev-preview-beta"
          [[registry.mirror]]
            location = "registry-quay-quay-enterprise.apps.{{ clusterName }}.{{ baseDomain }}/openshift-service-mesh-dev-preview-beta"

          [[registry]]
            prefix = ""
            location = "registry.redhat.io/rhoai"
          [[registry.mirror]]
            location = "registry-quay-quay-enterprise.apps.{{ clusterName }}.{{ baseDomain }}/rhoai"

          [[registry]]
            prefix = ""
            location = "registry.redhat.io/rhelai1"
          [[registry.mirror]]
            location = "registry-quay-quay-enterprise.apps.{{ clusterName }}.{{ baseDomain }}/rhelai1"

          [[registry]]
            prefix = ""
            location = "registry.redhat.io/rhaiis"
          [[registry.mirror]]
            location = "registry-quay-quay-enterprise.apps.{{ clusterName }}.{{ baseDomain }}/rhaiis"

          [[registry]]
            prefix = ""
            location = "registry.redhat.io/rhods"
          [[registry.mirror]]
            location = "registry-quay-quay-enterprise.apps.{{ clusterName }}.{{ baseDomain }}/rhods"

          [[registry]]
            prefix = ""
            location = "registry.redhat.io/rhel7"
          [[registry.mirror]]
            location = "registry-quay-quay-enterprise.apps.{{ clusterName }}.{{ baseDomain }}/rhel7"

          [[registry]]
            prefix = ""
            location = "registry.redhat.io/openshift-update-service"
          [[registry.mirror]]
            location = "registry-quay-quay-enterprise.apps.{{ clusterName }}.{{ baseDomain }}/openshift-update-service"

          [[registry]]
            prefix = ""
            location = "quay.io/argoproj"
          [[registry.mirror]]
            location = "registry-quay-quay-enterprise.apps.{{ clusterName }}.{{ baseDomain }}/argoproj"

- name: Create assisted-service-user-config ConfigMap
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: assisted-service-user-config
        namespace: multicluster-engine
      data:
        ALLOW_CONVERGED_FLOW: "false"
        PAUSE_PROVISIONED_BMHS: "false"

- name: Create AgentServiceConfig for disconnected environment
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: agent-install.openshift.io/v1beta1
      kind: AgentServiceConfig
      metadata:
        annotations:
          agent-install.openshift.io/enable-local-cluster-import: "true"
          unsupported.agent-install.openshift.io/assisted-service-configmap: assisted-service-user-config
        name: agent
      spec:
        mirrorRegistryRef:
          name: custom-registries
        databaseStorage:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 40Gi
        filesystemStorage:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 40Gi
        osImages:
        - cpuArchitecture: x86_64
          openshiftVersion: "4.20"
          rootFSUrl: "http://{{ quayHostname }}/rhcos-4.20.0-x86_64-live-rootfs.x86_64.img"
          url: "http://{{ quayHostname }}/rhcos-4.20.0-x86_64-live-iso.x86_64.iso"
          version: 9.6.20251023-0

- name: ACM ClusterImageSet reconciliation
  ansible.builtin.include_tasks:
    file: acm_cis.yaml
