---
- name: "Check if the repository archive file exists"
  ansible.builtin.stat:
    path: "{{ aap_archive_dest }}"
  register: __aap_archive_file_exists
  failed_when: false
  changed_when: false

# If the repository archive file exists, you can force a refresh by setting aap_archive_refresh to true
- name: "Package AAP configuration repository and serve via HTTP"
  block:
    - name: "Create temporary directory"
      ansible.builtin.file:
        path: "{{ aap_archive_tmp_dir }}"
        state: directory
        mode: "0750"

    - name: "Clone the configuration repository"
      ansible.builtin.git:
        repo: "{{ aap_config_repo }}"
        dest: "{{ aap_archive_tmp_dir }}"
        version: "{{ aap_config_version }}"

    - name: "Create archive file of the repository"
      ansible.builtin.archive:
        path: "{{ aap_archive_tmp_dir }}/"
        dest: "{{ aap_archive_dest }}"
        format: "{{ aap_archive_format }}"
      ignore_errors: "{{ ansible_check_mode }}"

    - name: "Set container recreate flag"
      ansible.builtin.set_fact:
        __aap_archive_container_recreate: true
  always:
    - name: "Remove temporary directory"
      ansible.builtin.file:
        path: "{{ aap_archive_tmp_dir }}"
        state: absent
      no_log: true
  when: >
    __aap_archive_file_exists.stat.exists is false or
    __aap_archive_file_exists.stat.exists is not defined or
    aap_archive_refresh | default(false) | bool

- name: "Run container to publish the AAP configuration"
  containers.podman.podman_container:
    name: "aap-archive-srv"
    image: "{{ aap_archive_image }}"
    authfile: "{{ aap_archive_authfile }}"
    state: started
    restart_policy: always
    recreate: "{{ __aap_archive_container_recreate | default(false) | bool }}"
    user: "1001"
    command: "/usr/libexec/s2i/run"
    security_opt:
      - no-new-privileges
    cap_drop:
      - ALL
    volumes:
      - "{{ aap_archive_dest }}:/opt/app-root/src/{{ aap_archive_filename }}:Z"
    publish:
      - "{{ aap_archive_port }}:8080"
