---
- name: Pause MachineConfigPool to prevent immediate churn
  environment:
    KUBECONFIG: "{{ workingDir }}/ocp-cluster/auth/kubeconfig"
  kubernetes.core.k8s:
    definition:
      apiVersion: machineconfiguration.openshift.io/v1
      kind: MachineConfigPool
      metadata:
        name: master
      spec:
        paused: true

- name: Apply mirroring and catalog resources
  environment:
    KUBECONFIG: "{{ workingDir }}/ocp-cluster/auth/kubeconfig"
  kubernetes.core.k8s:
    state: present
    src: "{{ workingDir }}/config/oc-mirror-workspace-post/working-dir/cluster-resources/{{ item }}"
  loop:
    - idms-oc-mirror.yaml
    - itms-oc-mirror.yaml
    - cs-redhat-operator-index-v4-20.yaml

- name: Unpause MachineConfigPools to trigger a single update cycle
  environment:
    KUBECONFIG: "{{ workingDir }}/ocp-cluster/auth/kubeconfig"
  kubernetes.core.k8s:
    definition:
      apiVersion: machineconfiguration.openshift.io/v1
      kind: MachineConfigPool
      metadata:
        name: master
      spec:
        paused: false

- name: Wait for MCO to acknowledge the change (Avoid the race condition)
  ansible.builtin.pause:
    seconds: 20

- name: Wait for MachineConfigPools to finish updating (In-Place)
  environment:
    KUBECONFIG: "{{ workingDir }}/ocp-cluster/auth/kubeconfig"
  kubernetes.core.k8s_info:
    api_version: machineconfiguration.openshift.io/v1
    kind: MachineConfigPool
    name: master
  register: mcp_status
  until:
    - mcp_status.resources[0].status.updatedMachineCount == mcp_status.resources[0].status.machineCount
    - mcp_status.resources[0].status.degradedMachineCount == 0
  retries: 60
  delay: 30
