---
- name: Configure operators
  block:

    - name: Include configure_operator
      ansible.builtin.include_tasks: configure_operator.yaml
      loop: "{{ operators }}"
      loop_control:
        loop_var: operator

  environment:
    KUBECONFIG: "{{ workingDir }}/ocp-cluster/auth/kubeconfig"
