---
# Set up Ironic for hardware configuration

- name: Deploy Metal3 common resources
  ansible.builtin.include_tasks: deploy_metal3_common.yaml

- name: Deploy Ironic pod
  ansible.builtin.include_tasks: deploy_ironic.yaml
