---
- name: Configure operators
  block:

    - name: Include configure_operator
      vars:
        default_operator_source: "cs-{{ mirror_rh_operator_catalog }}-v4-20"
      ansible.builtin.include_tasks: configure_operator.yaml
      loop: "{{ operators }}"
      loop_control:
        loop_var: operator

  environment:
    KUBECONFIG: "{{ workingDir }}/ocp-cluster/auth/kubeconfig"
