---
# Clean up Ironic deployment after hardware configuration is complete
- name: Stop and remove Ironic pod
  containers.podman.podman_pod:
    name: metal3-ironic
    state: absent

- name: Remove Ironic volumes
  containers.podman.podman_volume:
    name: "{{ item }}"
    state: absent
  loop:
    - metal3-ironic-conf
    - metal3-ironic-data
    - metal3-ironic-shared
  when: metal3_cleanup_volumes | default(false) | bool

- name: Remove Ironic secrets
  containers.podman.podman_secret:
    name: "{{ item }}"
    state: absent
  loop:
    - metal3-ironic-htpasswd
    - metal3-ca-bundle
    - metal3-ironic-username
    - metal3-ironic-password
    - ironic-vmedia-cert
    - ironic-vmedia-key
  when: metal3_cleanup_secrets | default(false) | bool
