---
- name: Configure operators
  block:

    - name: Disable default operator catalog sources
      when: disconnected | default(true) | bool
      ansible.builtin.command: |
        {{ workingDir }}/bin/oc patch OperatorHub cluster --type=json -p='[{"op":"replace","path":"/spec/disableAllDefaultSources","value":true}]'

    - name: Include configure_operator
      ansible.builtin.include_tasks: configure_operator.yaml
      loop: "{{ [storage_operators[blockStorageBackend]] + operators }}"
      loop_control:
        loop_var: operator

    - name: Pause for 3 minutes for InstallPlans to be created
      ansible.builtin.pause:
        minutes: 3

    - name: "Update operator versions"
      ansible.builtin.shell: |
        python ../scripts/operator_update.py "{{ [storage_operators[blockStorageBackend]] + operators }}" "False"

    - name: Print the output
      ansible.builtin.debug:
        var: operator_update_result.stdout_lines

    - name: Include specific tasks for the operators
      ansible.builtin.include_tasks: "../../operators/{{ operator.name }}/tasks.yaml"
      loop: "{{ [storage_operators[blockStorageBackend]] + operators }}"
      loop_control:
        loop_var: operator

  environment:
    KUBECONFIG: "{{ workingDir }}/ocp-cluster/auth/kubeconfig"
