---
- name: Download RHCOS live ISOs
  become: true
  ansible.builtin.get_url:
    url: "{{ iso_item.url }}"
    dest: "/var/www/html/{{ (iso_item.url | ansible.builtin.split('/'))[-1] }}"
    checksum: "{{ iso_item.checksum }}"
  loop: "{{ content_images.isos }}"
  loop_control:
    loop_var: iso_item
