---
- name: Initialize ISO version facts dictionary
  ansible.builtin.set_fact:
    iso_version_facts: {}

- name: Extract RHCOS ISOs from OpenShift release images
  ansible.builtin.include_tasks:
    file: download_content_single_version.yaml
  loop: "{{ openshift_versions }}"
  loop_control:
    loop_var: version_item
