---
- name: Ensure directory {{ workingDir }}/bin/ exists
  ansible.builtin.file:
    path: "{{ workingDir }}/bin/"
    state: directory

- name: Ensure {{ workingDir }}/dist/ exists
  ansible.builtin.file:
    path: "{{ workingDir }}/dist/"
    state: directory

- name: Ensure {{ workingDir }}/config/ exists
  ansible.builtin.file:
    path: "{{ workingDir }}/config/"
    state: directory

- name: Ensure {{ workingDir }}/logs/ exists
  ansible.builtin.file:
    path: "{{ workingDir }}/logs/"
    state: directory

- name: Download oc
  ansible.builtin.get_url:
    url: "{{ control_binaries.openshift_client.url }}"
    dest: "{{ workingDir }}/dist/openshift-client-linux.tar.gz"
    checksum: "{{ control_binaries.openshift_client.checksum }}"
    timeout: "{{ download_timeout }}"
  register: _download_oc
  retries: "{{ download_retries }}"
  delay: "{{ download_delay }}"
  until: _download_oc is success

- name: Unarchive openshift-client-linux.tar.gz to {{ workingDir }}/bin/
  ansible.builtin.unarchive:
    src: "{{ workingDir }}/dist/openshift-client-linux.tar.gz"
    dest: "{{ workingDir }}/bin/"
    remote_src: true

- name: Download helm
  ansible.builtin.get_url:
    url: "{{ control_binaries.helm.url }}"
    dest: "{{ workingDir }}/bin/helm"
    checksum: "{{ control_binaries.helm.checksum }}"
    mode: "0750"
    timeout: "{{ download_timeout }}"
  register: _download_helm
  retries: "{{ download_retries }}"
  delay: "{{ download_delay }}"
  until: _download_helm is success

- name: Download latest mirror registry available
  ansible.builtin.get_url:
    url: "{{ control_binaries.mirror_registry.url }}"
    dest: "{{ workingDir }}/dist/mirror-registry-amd64.tar.gz"
    checksum: "{{ control_binaries.mirror_registry.checksum }}"
    timeout: "{{ download_timeout }}"
  register: _download_mirror_registry
  retries: "{{ download_retries }}"
  delay: "{{ download_delay }}"
  until: _download_mirror_registry is success

- name: Unarchive mirror-registry-amd64.tar.gz to {{ workingDir }}/bin/
  ansible.builtin.unarchive:
    src: "{{ workingDir }}/dist/mirror-registry-amd64.tar.gz"
    dest: "{{ workingDir }}/bin/"
    remote_src: true

- name: Download latest oc-mirror available
  ansible.builtin.get_url:
    url: "{{ control_binaries.oc_mirror.url }}"
    dest: "{{ workingDir }}/dist/oc-mirror.tar.gz"
    checksum: "{{ control_binaries.oc_mirror.checksum }}"
    timeout: "{{ download_timeout }}"
  register: _download_oc_mirror
  retries: "{{ download_retries }}"
  delay: "{{ download_delay }}"
  until: _download_oc_mirror is success

- name: Unarchive oc-mirror.tar.gz to {{ workingDir }}/bin/
  ansible.builtin.unarchive:
    src: "{{ workingDir }}/dist/oc-mirror.tar.gz"
    dest: "{{ workingDir }}/bin/"
    remote_src: true

- name: Change oc-mirror permissions
  ansible.builtin.file:
    path: "{{ workingDir }}/bin/oc-mirror"
    mode: "0755"
