---
- name: Gather facts on a specific container
  containers.podman.podman_container_info:
    name: quay-app
  register: r_container_quay_app

- name: Install mirror-registry
  when:
    - r_container_quay_app.containers | default([]) | length == 0
  block:
    - name: Deploy mirror-registry
      no_log: true
      ansible.builtin.command: |
        {{ workingDir }}/bin/mirror-registry  install --quayHostname "{{ quayHostname }}" --quayRoot {{ workingDir }}/data --initPassword "{{ quayPassword }}" --initUser "{{ quayUser }}"
      register: r_mirror_registry

- name: Generate pull secret for internal mirror
  no_log: true
  ansible.builtin.set_fact:
    pullSecretInternal: '{"auths":{"{{ quayHostname }}:8443":{"auth":"{{ (quayUser + ":" + quayPassword) | ansible.builtin.b64encode }}"}}}'

- name: Combine pull secrets
  no_log: true
  ansible.builtin.set_fact:
    pullSecretNew: "{{ pullSecret | ansible.builtin.combine(pullSecretInternal, recursive=true) }}"

- name: Create pull-secret file with the combination
  no_log: true
  ansible.builtin.copy:
    content: "{{ pullSecretNew }}"
    dest: "{{ pullSecretPath }}"

- name: Create pull-secret internal file with the combination
  no_log: true
  ansible.builtin.copy:
    content: "{{ pullSecretInternal }}"
    dest: "{{ workingDir }}/config/pull-secret.internal.json"

- name: Copy imagesetconfiguration-core.yaml for core components
  ansible.builtin.template:
    src: ../../templates/imagesetconfiguration-core.yaml.j2
    dest: "{{ workingDir }}/config/imagesetconfiguration-core.yaml"

- name: Change oc-mirror permissions
  ansible.builtin.file:
    path: "{{ workingDir }}/bin/oc-mirror"
    mode: "0755"

- name: Start oc-mirror process for core components
  ansible.builtin.shell: >
    {{ workingDir }}/bin/oc-mirror --v2
    --log-level {{ ocMirrorLogLevel }}
    --authfile {{ pullSecretPath }}
    --dest-tls-verify=false
    -c {{ workingDir }}/config/imagesetconfiguration-core.yaml
    --workspace file://{{ workingDir }}/config/oc-mirror-workspace-core
    --parallel-images 10 --parallel-layers 10
    --retry-times 10 --retry-delay 0
    docker://{{ quayHostname }}:8443
    > {{ workingDir }}/logs/oc-mirror-core.progress.$(date +%s).log 2>&1
  retries: 10
  delay: 10
  register: r_oc_mirror_core
  until: r_oc_mirror_core is success