---
# Invoked from mirror_cache.yaml with loop_var __mirror_cache_imageset_path

- name: Start oc-mirror process ({{ __mirror_cache_imageset_path | basename }})
  ansible.builtin.shell: >
    {{ workingDir }}/bin/oc-mirror --v2
    --log-level {{ ocMirrorLogLevel }}
    --authfile {{ workingDir }}/config/pull-secret-cache.json
    --dest-tls-verify=false
    -c {{ __mirror_cache_imageset_path }}
    --workspace file://{{ workingDir }}/config/oc-mirror-cache-workspace
    --parallel-images 10 --parallel-layers 10
    --retry-times 10 --retry-delay 0
    docker://{{ dc_cache_address }}
    > {{ workingDir }}/logs/oc-mirror-cache.{{ __mirror_cache_imageset_path | basename | regex_replace('\.ya?ml$', '') }}.$(date +%s).log 2>&1
  retries: 5
  delay: 10
  register: __r_oc_mirror_cache_item
  until: __r_oc_mirror_cache_item is success
