---
- name: Copy core imagesetconfiguration.yaml
  ansible.builtin.template:
    src: ../../templates/imagesetconfiguration-core.yaml.j2
    dest: "{{ workingDir }}/config/imagesetconfiguration-core.yaml"

- name: Mirror core OpenShift installation images
  ansible.builtin.shell: |
    {{ workingDir }}/bin/oc-mirror --v2 \
    {{ '--dry-run' if (mirror_dry_run | default(false) | bool) else '' }} \
    --log-level {{ ocMirrorLogLevel }} \
    --authfile {{ pullSecretPath }} \
    --dest-tls-verify=false \
    -c {{ workingDir }}/config/imagesetconfiguration-core.yaml \
    --workspace file://{{ workingDir }}/config/oc-mirror-workspace \
    --parallel-images 10 --parallel-layers 10 \
    --retry-times 10 --retry-delay 0 \
    docker://{{ quayHostname }}:8443 \
    > {{ workingDir }}/logs/oc-mirror-core.progress.$(date +%s).log 2>&1
  retries: "{{ 1 if (mirror_dry_run | default(false) | bool) else 10 }}"
  delay: "{{ 0 if (mirror_dry_run | default(false) | bool) else 10 }}"
  register: r_oc_mirror_core
  until: r_oc_mirror_core is success
