---
- name: Ensure enclave config dir exists
  ansible.builtin.file:
    path: "{{ lookup('env','HOME') }}/.config/enclave"
    state: directory
  register: _enclave_config_dir

- name: Create symlink for kubeconfig in user's home
  ansible.builtin.file:
    src: "{{ workingDir }}/ocp-cluster/auth/kubeconfig"
    dest: "{{ _enclave_config_dir.path }}/kubeconfig"
    state: link
