---
- name: Pause for 3 minutes for the baremetal to be rebooted
  ansible.builtin.pause:
    minutes: 3

- name: Wait for bootstrap to be completed
  ansible.builtin.command: |
    {{ workingDir }}/bin/openshift-install --dir {{ workingDir }}/ocp-cluster/ agent wait-for bootstrap-complete --log-level=debug

- name: Wait for installation to be completed
  ansible.builtin.command: |
    {{ workingDir }}/bin/openshift-install --dir {{ workingDir }}/ocp-cluster/ agent wait-for install-complete  --log-level=debug

- name: Detach virtual media from hosts
  loop: "{{ agent_hosts }}"
  loop_control:
    loop_var: agent_host
  ansible.builtin.include_tasks:
    file: tasks/configure_hardware_ironic_detach_vmedia.yaml

- name: Cleanup Ironic
  ansible.builtin.include_tasks:
    file: tasks/configure_hardware_ironic_cleanup.yaml

- name: Verify pod Capacity on all master nodes
  block:
    - name: Wait for KubeletConfig to be recognized by the cluster
      kubernetes.core.k8s_info:
        kind: KubeletConfig
        name: set-master-max-pods
      register: kubeconfig_status
      retries: "{{ k8s_retries }}"
      delay: "{{ k8s_delay }}"
      until: kubeconfig_status.resources | length > 0

    - name: Get master node capacities
      kubernetes.core.k8s_info:
        kind: Node
        label_selectors:
          - pools.operator.machineconfiguration.openshift.io/master
      register: master_nodes

    - name: Assert that all master nodes report the correct maxPods
      ansible.builtin.assert:
        that:
          - item.status.capacity.pods == {{ masterMaxPods }}
        fail_msg: "Node {{ item.metadata.name }} reports {{ item.status.capacity.pods }} pods, expected {{ masterMaxPods }}"
        success_msg: "Node {{ item.metadata.name }} correctly reports {{ masterMaxPods }} pods."
      loop: "{{ master_nodes.resources }}"
      loop_control:
        label: "{{ item.metadata.name }}"
