- name: Create local export directory
  ansible.builtin.file:
    path: "{{ workingDir }}/data/clair"
    state: directory
    mode: '0777'

- name: Create minimal Clair config for export
  ansible.builtin.copy:
    dest: "{{ workingDir }}/data/clair/config.yaml"
    content: |
      http_listen_addr: :8080
      introspection_addr: :8081
      indexer:
        connstring: ""
        scanlock_retry: 10
        layer_scan_concurrency: 5
      matcher:
        connstring: ""
        max_conn_pool: 100
      notifier:
        connstring: ""
        delivery_interval: 1m

- name: Export vulnerability data on Landing Zone
  ansible.builtin.shell: |
    {{ workingDir }}/bin/clairctl --config {{ workingDir }}/data/clair/config.yaml export-updaters {{ workingDir }}/data/clair/updates.json.gz

- name: Ensure directory /var/www/html/clair/
  become: true
  ansible.builtin.file:
    path: "/var/www/html/clair/"
    state: directory

- name: Copy to /var/www/html/clair/
  become: true
  ansible.builtin.copy:
    src: "{{ workingDir }}/data/clair/updates.json.gz"
    dest: "/var/www/html/clair/updates.json.gz"

- name: Create Clair Import Role
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: rbac.authorization.k8s.io/v1
      kind: Role
      metadata:
        name: clair-import
        namespace: quay-enterprise
      rules:
        - apiGroups: [""]
          resources: ["pods"]
          verbs: ["get", "list", "exec"]

- name: Create Clair Import RoleBinding
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: rbac.authorization.k8s.io/v1
      kind: RoleBinding
      metadata:
        name: clair-import
        namespace: quay-enterprise
      subjects:
        - kind: ServiceAccount
          name: clair-import
          namespace: openshift-pipelines
      roleRef:
        kind: Role
        name: clair-import
        apiGroup: rbac.authorization.k8s.io
