---
# Quay disconnected tasks: imageset for oc-mirror and mirror run.
# This file is included only when disconnected | default(true).

- name: Collect plugin registries for registries.conf
  ansible.builtin.include_tasks:
    file: "../../playbooks/tasks/collect_plugin_registries.yaml"

- name: Merge core and post imagesetconfiguration
  vars:
    imageset_core: "{{ lookup('file', workingDir ~ '/config/imagesetconfiguration-core.yaml') | from_yaml }}"
    imageset_post: "{{ lookup('file', workingDir ~ '/config/imagesetconfiguration-post.yaml') | from_yaml }}"
  set_fact:
    imageset_internal: "{{ imageset_core | combine(imageset_post, recursive=True, list_merge='append') }}"

- name: Write merged imagesetconfiguration to imagesetconfiguration.internal.yaml
  copy:
    content: "{{ imageset_internal | to_nice_yaml }}"
    dest: "{{ workingDir}}/config/imagesetconfiguration.internal.yaml"

- name: Replace registry.redhat.io with internal quay
  ansible.builtin.replace:
    path: "{{ workingDir }}/config/imagesetconfiguration.internal.yaml"
    regexp: 'catalog: registry.redhat.io'
    replace: "catalog: {{ quayHostname }}:8443"

- name: Ensure .config/containers/ exists
  ansible.builtin.file:
    path: "{{ lookup('env','HOME') }}/.config/containers/"
    state: directory

- name: Generate registries.conf for the oc-mirror process
  ansible.builtin.template:
    src: "../../templates/registries.conf.j2"
    dest: "{{ lookup('env','HOME') }}/.config/containers/registries.conf"

- name: Start oc-mirror process to Quay
  ansible.builtin.shell: |
    _retry=1
    _max_retries=10
    _delay=10
    until {{ workingDir }}/bin/oc-mirror --v2 \
      --log-level {{ ocMirrorLogLevel }} \
      --authfile {{ workingDir }}/config/pull-secret.quay.json \
      -c {{ workingDir }}/config/imagesetconfiguration.internal.yaml \
      --workspace file://{{ workingDir }}/config/oc-mirror-workspace-quay \
      docker://registry-quay-quay-enterprise.apps.{{ clusterName }}.{{ baseDomain }} \
      --dest-tls-verify=false \
      --src-tls-verify=false \
      --parallel-images 10 \
      --parallel-layers {{ 1 if quayBackend == 'LocalStorage' else 10 }} \
      --retry-times 10 \
      --retry-delay 0 \
      --image-timeout 40m0s \
      > {{ workingDir }}/logs/oc-mirror.progress.quay.$(date +%s).log 2>&1
    do
      if [ $_retry -ge $_max_retries ]; then
        echo "Max retries reached"
        exit 1
      fi
      echo "Some images failed to mirror. Retrying ($_retry of $_max_retries)"
      _retry=$((_retry+1))
      sleep $_delay
    done
  register: r_oc_mirror_quay
  # Async run
  async: 14400 # 4 hours timeout
  poll: 0      # Start immediately, don't wait

- name: Save async job ID for later reference
  ansible.builtin.copy:
    content: "{{ r_oc_mirror_quay.ansible_job_id }}"
    dest: "{{ workingDir }}/logs/quay-mirror.async_job_id"
