- name: Create or update quay-config Secret
  no_log: true
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: quay-config
        namespace: quay-enterprise
      type: Opaque
      stringData:
        config.yaml: |
          ALLOW_PULLS_WITHOUT_STRICT_LOGGING: false
          AUTHENTICATION_TYPE: Database
          DEFAULT_TAG_EXPIRATION: 2w
          FEATURE_USER_INITIALIZE: true
          SUPER_USERS:
            - quayadmin
          BROWSER_API_CALLS_XHR_ONLY: false
          FEATURE_USER_CREATION: false
          CREATE_NAMESPACE_ON_PUSH: true
          DISTRIBUTED_STORAGE_CONFIG:
            local_us:
              - {{ quayBackend }}
              - {{ ((quayBackendDefaults
                   | combine(quayBackendRGWDefaults)
                   | combine(quayBackendRGWConfiguration))
                   if quayBackend == 'RadosGWStorage'
                   else (quayBackendDefaults
                   | combine(quayBackendLocalStorageConfiguration | default({})))
                   if quayBackend == 'LocalStorage'
                   else quayBackendDefaults)
                   | to_yaml }}
          DISTRIBUTED_STORAGE_DEFAULT_LOCATIONS:
            - local_us

          ENTERPRISE_LOGO_URL: /static/img/RH_Logo_Quay_Black_UX-horizontal.svg
          FEATURE_BUILD_SUPPORT: false
          FEATURE_DIRECT_LOGIN: true
          FEATURE_MAILING: false
          REGISTRY_TITLE: Red Hat Quay
          REGISTRY_TITLE_SHORT: Red Hat Quay
          SETUP_COMPLETE: true
          TAG_EXPIRATION_OPTIONS:
            - 2w
          TEAM_RESYNC_STALE_TIME: 60m
          TESTING: false
          FEATURE_PROXY_STORAGE: {{ quayFeatureProxyStorage | bool | lower }}
          FEATURE_QUOTA_MANAGEMENT: {{ quayFeatureQuotaManagement | bool | lower }}
          MAXIMUM_LAYER_SIZE: {{ quayMaximumLayerSize }}
        clair-config.yaml: |
          indexer:
            airgap: true
            scanner:
              repo:
                rhel-repository-scanner:
                  repo2cpe_mapping_file: "/data/repository-to-cpe.json"
              package:
                rhel_containerscanner:
                  name2repos_mapping_file: "/data/container-name-repos-map.json"
          matcher:
            disable_updaters: true
  register: r_quay_config_secret
  retries: "{{ k8s_retries }}"
  delay: "{{ k8s_delay }}"
  until: r_quay_config_secret is success

- name: Run storage plugin Quay tasks
  ansible.builtin.include_tasks:
    file: "{{ playbook_dir }}/../plugins/{{ storage_plugin }}/tasks/quay.yaml"
  when: lookup('ansible.builtin.fileglob', playbook_dir ~ '/../plugins/' ~ storage_plugin ~ '/tasks/quay.yaml') | length > 0

- name: Ensure DNS for Quay route in /etc/hosts uses Ingress VIP
  ansible.builtin.lineinfile:
    path: /etc/hosts
    line: "{{ ingressVIP }} registry-quay-quay-enterprise.apps.{{ clusterName }}.{{ baseDomain }}"
    regexp: ".*registry-quay-quay-enterprise.apps.{{ clusterName }}.{{ baseDomain }}.*"
    state: present
  become: true

- name: Wait for QuayRegistry to be available
  kubernetes.core.k8s_info:
    api_version: quay.redhat.com/v1
    kind: QuayRegistry
    name: registry
    namespace: quay-enterprise
  register: quay_registry
  retries: 60
  delay: 10
  until:
    - quay_registry.resources is defined
    - quay_registry.resources | length > 0
    - quay_registry.resources[0].status.conditions is defined
    - quay_registry.resources[0].status.conditions | selectattr('type', 'equalto', 'Available') | selectattr('status', 'equalto', 'True') | list | length > 0


- name: Create user
  no_log: true
  ansible.builtin.uri:
    url: "https://registry-quay-quay-enterprise.apps.{{ clusterName }}.{{ baseDomain }}/api/v1/user/initialize"
    method: POST
    headers:
      Content-Type: application/json
    validate_certs: false
    return_content: yes
    status_code:
      - 200
      - 400
    body_format: json
    body:
      username: "{{ quayUser }}"
      password: "{{ quayPassword }}"
      email: "ecoeng-sovereign-cloud@redhat.com"
      access_token: true
  register: r_quay_user
  retries: 10
  delay: 30
  until:
    - r_quay_user is defined
    - r_quay_user.status | default(0) == 200 or r_quay_user.json.message | default("") == "Cannot initialize user in a non-empty database"

- name: Generate pull secret for internal mirror
  no_log: true
  ansible.builtin.set_fact:
    pullSecretQuay: >-
      {"auths":{
      "{{ quayHostname }}:8443":{"auth":"{{ (quayUser + ":" + quayPassword) | ansible.builtin.b64encode }}"},
      "registry-quay-quay-enterprise.apps.{{ clusterName }}.{{ baseDomain }}":
      {"auth":"{{ (quayUser + ":" + quayPassword) | ansible.builtin.b64encode }}"}
      }}

- name: Combine pull secrets for connected mode
  no_log: true
  when: not (disconnected | default(true))
  ansible.builtin.set_fact:
    pullSecretNew: "{{ pullSecret | ansible.builtin.combine(pullSecretQuay, recursive=true) }}"

- name: Set pull secret for disconnected (no combine)
  no_log: true
  when: disconnected | default(true)
  ansible.builtin.set_fact:
    pullSecretNew: "{{ pullSecretQuay }}"

- name: Patch cluster pull-secret
  no_log: true
  kubernetes.core.k8s:
    state: patched
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: pull-secret
        namespace: openshift-config
      stringData:
        .dockerconfigjson: "{{ pullSecretNew | to_json }}"
      type: kubernetes.io/dockerconfigjson
  register: r_patch_cluster_pullsecret
  retries: "{{ k8s_retries }}"
  delay: "{{ k8s_delay }}"
  until: r_patch_cluster_pullsecret is success

- name: Create pull-secret file with the combination
  no_log: true
  ansible.builtin.copy:
    content: "{{ pullSecretQuay }}"
    dest: "{{ workingDir }}/config/pull-secret.quay.json"

- name: Quay disconnected (oc-mirror setup and run)
  when: disconnected | default(true)
  ansible.builtin.include_tasks:
    file: quay_disconnected.yaml
