---

- name: Include deployment defaults
  ansible.builtin.include_vars: ../../defaults/deployment.yaml

- name: Include global deployment vars
  ansible.builtin.include_vars: "{{ vars_file | default('../../config/global.yaml') }}"

- name: Include certificate vars
  ansible.builtin.include_vars: ../../config/certificates.yaml

- name: Include cloud infra vars
  ansible.builtin.include_vars: ../../config/cloud_infra.yaml

- name: Include common configuration
  ansible.builtin.include_vars: "../../defaults/{{ config_file }}"
  loop:
    - content_images.yaml
    - control_binaries.yaml
    - operators.yaml
    - platforms.yaml
    - catalogs.yaml
    - mirror_registry.yaml
    - quay_operator.yaml
    - k8s.yaml
  loop_control:
    loop_var: config_file

- name: Ensure storage plugin is in enabled_plugins
  ansible.builtin.set_fact:
    enabled_plugins: "{{ enabled_plugins | union([storage_plugin]) }}"
