#!/bin/bash
# Shared ODF configuration utilities
#
# Provides functions for loading ODF external config and Quay RGW config
# from either environment variables (backward compat) or LZ config files
# generated by setup_ceph.sh.
#
# Usage:
#   source "${ENCLAVE_DIR}/scripts/lib/odf.sh"
#   append_odf_extra_vars
#
# Prerequisites:
#   - SSH_OPTS, LZ_SSH, LZ_USER must be set (via ssh.sh)
#   - EXTRA_VARS_CONTENT must be initialized
#   - output.sh must be sourced (for info function)
#
# Functions:
#   append_odf_extra_vars  - Append ODF config to EXTRA_VARS_CONTENT

# Append ODF external config and Quay RGW config to EXTRA_VARS_CONTENT.
# Env vars take precedence over LZ config files (backward compat).
# shellcheck disable=SC2086  # SSH_OPTS needs word splitting
append_odf_extra_vars() {
    local odf_config_file="${LZ_HOME:-/home/${LZ_USER:-cloud-user}}/ceph-config/odf_external_config.json"
    local rgw_config_file="${LZ_HOME:-/home/${LZ_USER:-cloud-user}}/ceph-config/quay_backend_rgw_config.yaml"

    # ODF external config: env var first, then LZ file
    if [ -n "${ODF_EXTERNAL_CONFIG:-}" ]; then
        EXTRA_VARS_CONTENT="${EXTRA_VARS_CONTENT}odfExternalConfig: '${ODF_EXTERNAL_CONFIG}'
"
        info "ODF external config: from environment"
    elif ssh $SSH_OPTS "$LZ_SSH" "test -f $odf_config_file" 2>/dev/null; then
        local odf_config
        odf_config=$(ssh $SSH_OPTS "$LZ_SSH" "cat $odf_config_file")
        EXTRA_VARS_CONTENT="${EXTRA_VARS_CONTENT}odfExternalConfig: '${odf_config}'
"
        info "ODF external config: from LZ ceph-config"
    fi

    # Quay RGW config: env var first, then LZ file
    if [ -n "${QUAY_BACKEND_RGW_CONFIG:-}" ]; then
        EXTRA_VARS_CONTENT="${EXTRA_VARS_CONTENT}quayBackend: RadosGWStorage
quayBackendRGWConfiguration: ${QUAY_BACKEND_RGW_CONFIG}
"
        info "Quay backend: RadosGWStorage (from environment)"
    elif ssh $SSH_OPTS "$LZ_SSH" "test -f $rgw_config_file" 2>/dev/null; then
        local rgw_config
        rgw_config=$(ssh $SSH_OPTS "$LZ_SSH" "cat $rgw_config_file")
        EXTRA_VARS_CONTENT="${EXTRA_VARS_CONTENT}quayBackend: RadosGWStorage
quayBackendRGWConfiguration: ${rgw_config}
"
        info "Quay backend: RadosGWStorage (from LZ ceph-config)"
    fi
}
