apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: vmaas
  namespace: openshift-acm-policies
placementRef:
  apiGroup: apps.open-cluster-management.io
  kind: PlacementRule
  name: vmaas
subjects:
- apiGroup: policy.open-cluster-management.io
  kind: Policy
  name: vmaas
