---
# Wait for mirror of operator and additional images
#
# The mirror of operator images and additional images is now performed in an async way
# This playbook will run the tasks needed to wait for that async task to finish
#
# Usage:
#   ansible-playbook playbooks/wait_operator_mirror.yaml -e workingDir=/home/cloud-user

- name: Wait operator mirror
  hosts: localhost
  gather_facts: false
  environment:
    PATH: "{{ workingDir }}/bin:{{ lookup('env', 'PATH') }}"
  tasks:
    - name: Load common variables
      ansible.builtin.include_tasks:
        file: common/load-vars.yaml
        apply:
          tags: always
      tags: always

    - name: Display operator installation mode
      ansible.builtin.debug:
        msg: "Installing operators in {{ 'disconnected' if (disconnected | default(true)) else 'connected' }} mode"
      tags: always

    - name: Wait for the async task mirror_registry_post
      when: disconnected | default(true) | bool
      ansible.builtin.include_tasks:
        file: tasks/wait_operator_mirror.yaml
