name: Auto Label

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

# Only one labeler run per PR
concurrency:
  group: labeler-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  # Area labels based on file paths
  area-labels:
    name: Area Labels
    runs-on: [self-hosted, pr-validation]
    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/labeler@8558fd74291d67161a8a78ce36a881fa63b766a9 # v5.0.2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: .github/labeler.yml
          sync-labels: true

  # Size labels based on lines changed
  size-labels:
    name: Size Labels
    runs-on: [self-hosted, pr-validation]
    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: codelytv/pr-size-labeler@4ec67706cd878fbc1c8db0a5dcd28b6bb412e85a # v1.10.3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          xs_label: 'size/XS'
          xs_max_size: '9'
          s_label: 'size/S'
          s_max_size: '99'
          m_label: 'size/M'
          m_max_size: '499'
          l_label: 'size/L'
          l_max_size: '999'
          xl_label: 'size/XL'
          fail_if_xl: 'false'
