#!/bin/bash
# Add custom CA certificate to OpenShift cluster trust bundle
#
# This script is used in CI after post-install to add the self-signed CA
# (generated by generate_enclave_vars.sh) to the cluster's trusted CA bundle.
# Without this, the authentication operator reports degraded status because
# the ingress certificate is signed by an untrusted CA.
#
# This is NOT needed for production deployments where certificates are
# signed by publicly trusted CAs.
#
# Usage: ./trust_custom_ca.sh

set -euo pipefail

# Detect Enclave repository root
SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"
ENCLAVE_DIR="$(cd -- "${SCRIPT_DIR}/../.." &>/dev/null && pwd)"

# Source shared utilities
source "${ENCLAVE_DIR}/scripts/lib/output.sh"
source "${ENCLAVE_DIR}/scripts/lib/validation.sh"
source "${ENCLAVE_DIR}/scripts/lib/config.sh"
source "${ENCLAVE_DIR}/scripts/lib/network.sh"
source "${ENCLAVE_DIR}/scripts/lib/ssh.sh"

# Validate required environment variables
require_env_var "DEV_SCRIPTS_PATH"

# Determine cluster name for dynamic config file
ENCLAVE_CLUSTER_NAME="${ENCLAVE_CLUSTER_NAME:-enclave-test}"

# Source dev-scripts configuration
load_devscripts_config

# Configuration
CLUSTER_NAME="${CLUSTER_NAME:-enclave-test}"
LZ_VM_NAME="${CLUSTER_NAME}_landingzone_0"

# Get Landing Zone IP using network utility
CLUSTER_NETWORK="${EXTERNAL_SUBNET_V4}"
CLUSTER_IP=$(get_vm_ip_on_network "$LZ_VM_NAME" "$CLUSTER_NETWORK")

if [ -z "$CLUSTER_IP" ]; then
    error "Could not determine Landing Zone IP address"
    exit 1
fi

# Setup SSH configuration
setup_ssh_config "$CLUSTER_IP"

info "Adding custom CA to cluster trust bundle..."
info "Landing Zone: $CLUSTER_IP"

# Verify SSH connectivity
if ! ssh_test_connection; then
    error "Cannot connect to Landing Zone at $CLUSTER_IP"
    exit 1
fi

# Extract CA cert from certificates.yaml and add it to cluster trust on the LZ
# shellcheck disable=SC2086
ssh $SSH_OPTS "$LZ_SSH" bash <<'EOSSH'
set -euo pipefail

KUBECONFIG=/home/cloud-user/ocp-cluster/auth/kubeconfig
export KUBECONFIG
export PATH="/home/cloud-user/bin:$PATH"

CERTS_FILE="/home/cloud-user/enclave/config/certificates.yaml"

if [ ! -f "$CERTS_FILE" ]; then
    echo "No certificates.yaml found, skipping CA trust setup"
    exit 0
fi

# Extract sslCACertificate from certificates.yaml
CA_CERT=$(python3 -c '
import yaml, sys
with open(sys.argv[1]) as f:
    data = yaml.safe_load(f)
cert = data.get("sslCACertificate", "")
if cert:
    print(cert.strip())
' "$CERTS_FILE")

if [ -z "$CA_CERT" ]; then
    echo "No sslCACertificate found in certificates.yaml, skipping"
    exit 0
fi

echo "Creating custom-ca-bundle ConfigMap in openshift-config..."
oc create configmap custom-ca-bundle \
    --from-literal=ca-bundle.crt="$CA_CERT" \
    -n openshift-config \
    --dry-run=client -o yaml | oc apply -f -

echo "Patching Proxy/cluster to trust the custom CA..."
oc patch proxy/cluster \
    --type=merge \
    -p '{"spec":{"trustedCA":{"name":"custom-ca-bundle"}}}'

echo "Custom CA added to cluster trust bundle"
EOSSH

success "Custom CA trust configured"
